# Generated by Django 4.1 on 2022-09-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('-is_active', '-created')},
        ),
    ]
